[package]
name = "omr-img-corrector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = { version = "0.76.4", default-features = true, features = ["highgui", "imgcodecs"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
