[package]
name = "omr-img-corrector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
omr-img-corrector-sdk = { version="0.1.0", path = "../lib" }
rand = "0.8.5"
walkdir = "2.3.3"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
