[package]
name = "omr-img-corrector-cli"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.1"
omr-img-corrector-sdk = { version="0.9.0", path = "../lib" }
once_cell = "1.17.1"
walkdir = "2.3.3"
